data:
    name: 'kaggle_rhd'
    validation_size: 5000
    cache_in_memory: true
    scoremap_variance: 7
model:
    name: 'mnist_baseline'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.0001
train_iter: 1000
eval_set: 'val'
