data:
    name: 'kaggle_rhd'
    validation_size: 5000
    cache_in_memory: false
model:
    name: 'mnist_fc'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.001
train_iter: 200000
eval_set: 'val'
validation_interval: 500
