data:
    name: 'kaggle_rhd'
    validation_size: 480
    cache_in_memory: true
    augmentation:
        bbox_distort: false
        random_rotation: true
        random_brightness: true
        random_saturation: true
model:
    name: 'resnet_fc'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.0001
train_iter: 120000
validation_interval: 500
eval_set: 'val'
weights: 'resnet_v2_152/resnet_v2_152.ckpt'
