data:
    name: 'kaggle_rhd'
    validation_size: 500
    cache_in_memory: false
    disk_radius: 8
model:
    name: 'resnet_disks'
    batch_size: 32
    eval_batch_size: 25
    learning_rate: 0.0001
    output_kernel: [3, 3]
train_iter: 80000
validation_interval: 1000
eval_set: 'val'
weights: 'resnet_v2_152/resnet_v2_152.ckpt'
