data:
    name: 'kaggle_rhd'
    validation_size: 5000
    cache_in_memory: true
    scoremap_variance: 7
model:
    name: 'resnet_baseline'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.0001
    output_kernel: [3, 3]
train_iter: 1000
eval_set: 'val'
weights: 'resnet_v2_50/resnet_v2_50.ckpt'
