data:
    name: 'kaggle_rhd'
    data_format: 'channels_last'
model:
    name: 'resnet_baseline'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.0001
    output_kernel: [3, 3]
train_iter: 1000
eval_set: 'val'
data_format: 'channels_first'
