data:
    name: 'kaggle_rhd'
    validation_size: 480
    cache_in_memory: true
model:
    name: 'resnet_baseline'
    batch_size: 32
    eval_batch_size: 25
    learning_rate: 0.0001
train_iter: 50000
validation_interval: 500
eval_set: 'val'
weights: 'resnet_v2_100/resnet_v2_100.ckpt'
