data:
    name: 'kaggle_rhd'
    validation_size: 480
    cache_in_memory: false
    scoremap_variance: 20
model:
    name: 'resnet_baseline'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.0001
    output_kernel: [3, 3]
train_iter: 10000
validation_interval: 1000
eval_set: 'val'
weights: 'resnet_v2_50/resnet_v2_50.ckpt'
